import type { SiteConfig } from "./types/site-config";

// Generic placeholder so this template runs/builds standalone. BuildPilot's
// document-generation stage overwrites this file with the real, validated
// business data (and LLM-authored cinematic copy) for each customer — do
// not add business-specific content here. See docs/DEVIN_3D_WEBSITE_SPEC.md
// (buildpilot-platform repo) for what each field controls.
const assetRoot = "/assets/cafe";

export const siteConfig: SiteConfig = {
  variant: "cinematic",
  businessName: "BuildPilot Starter",
  purpose: "A generic cinematic starter site generated by BuildPilot.",
  contact: {},
  palette: {
    background: "#160F0A",
    surface: "#20160F",
    text: "#F3E8DC",
    muted: "#BCA994",
    accent: "#C68A3D",
    accentHover: "#E0A75C",
  },
  navigation: [
    { label: "Highlights", href: "#products" },
    { label: "Enquire", href: "#enquiry" },
  ],
  assets: {
    collection: "cafe",
    root: assetRoot,
    framesDirectory: `${assetRoot}/frames`,
    productsDirectory: `${assetRoot}/products`,
  },
  hero: {
    directory: `${assetRoot}/frames`,
    poster: `${assetRoot}/frames/ezgif-frame-001.jpg`,
    filePrefix: "ezgif-frame-",
    fileExtension: "jpg",
    framePadding: 3,
    firstFrame: 1,
    frameCount: 300,
    width: 1920,
    height: 1080,
    scrollHeightVh: 600,
    maxDevicePixelRatio: 2,
    maxCachedFrames: 48,
    loadConcurrency: 6,
    narrowViewportBreakpoint: 768,
    focalPoint: {
      wide: { x: 0.5, y: 0.5 },
      narrow: { x: 0.62, y: 0.5 },
    },
    chapters: [
      {
        id: "opening",
        from: 0,
        to: 0.24,
        align: "left",
        eyebrow: "Welcome",
        heading: "This is the generic BuildPilot starter template.",
        body: "Customer-specific content is added on top of this base by the automated build process.",
        showScrollCue: true,
      },
      {
        id: "mid",
        from: 0.34,
        to: 0.6,
        align: "right",
        eyebrow: "What makes it different",
        heading: "Every detail is configured, not hardcoded.",
        body: "Palette, copy, and imagery all come from src/site.config.ts.",
      },
      {
        id: "closing",
        from: 0.72,
        to: 1,
        align: "left",
        eyebrow: "Get started",
        heading: "Ready when you are.",
        body: "Send an enquiry to learn more.",
        primaryCta: { label: "Send an enquiry", href: "#enquiry" },
        secondaryCta: { label: "See highlights", href: "#products" },
      },
    ],
  },
  productsSection: {
    id: "products",
    eyebrow: "What we offer",
    heading: "Highlights",
    body: "A quick look at what this business offers.",
    scrollHeightVh: 500,
    items: [
      { category: "Highlight", name: "Classic Cappuccino", description: "Placeholder item.", image: "classic-cappuccino.jpg" },
      { category: "Highlight", name: "Double Espresso", description: "Placeholder item.", image: "double-espresso.jpg" },
      { category: "Highlight", name: "Iced Caramel Latte", description: "Placeholder item.", image: "iced-caramel-latte.jpg" },
      { category: "Highlight", name: "Pour Over Coffee", description: "Placeholder item.", image: "pour-over-coffee.jpg" },
    ],
  },
  enquirySection: {
    id: "enquiry",
    eyebrow: "Get in touch",
    heading: "Tell us what you need.",
    body: "We'll get back to you shortly.",
    submitLabel: "Send enquiry",
    enquiryTypes: ["General enquiry"],
    disconnectedMessage: "Form submission is not connected yet.",
    consentLabel: "I agree to be contacted about this enquiry.",
  },
} satisfies SiteConfig;
