// Generated by BuildPilot from the validated call transcript for NHS Medical Fitness Center.
// Do not hand-edit business data here across rebuilds — update the source
// requirements and regenerate instead. See src/types/site-config.ts (starter
// template) for the full SiteConfig shape (cinematic or plain variant) and
// docs/DEVIN_3D_WEBSITE_SPEC.md for how each field is used.
import type { SiteConfig } from "./types/site-config";

export const siteConfig: SiteConfig = {
  "variant": "cinematic",
  "businessName": "NHS Medical Fitness Center",
  "purpose": "General and cosmetic dental clinic",
  "targetAudience": "Families in Al Barsha and nearby areas, plus young professionals interested in cosmetic treatments like whitening and Invisalign",
  "contact": {
    "email": "contact@brightsmiledubai.com",
    "address": "Al Barsha 1, near the Mall of the Emirates, Dubai"
  },
  "palette": {
    "background": "#F8FAFC",
    "surface": "#FFFFFF",
    "text": "#0F172A",
    "muted": "#64748B",
    "accent": "#0284C7",
    "accentHover": "#0369A1"
  },
  "enquirySection": {
    "id": "enquiry",
    "eyebrow": "Get in Touch",
    "heading": "Schedule Your Visit",
    "body": "Our team is ready to assist you with any questions about our services, insurance coverage, or availability. We look forward to welcoming you to our clinic in Al Barsha.",
    "submitLabel": "Send enquiry",
    "enquiryTypes": [
      "General Dental Care",
      "Cosmetic Dentistry",
      "Invisalign Consultation",
      "Insurance & Billing"
    ],
    "disconnectedMessage": "Form submission is not connected yet.",
    "consentLabel": "I agree to be contacted by NHS Medical Fitness Center regarding my enquiry."
  },
  "navigation": [
    {
      "label": "Highlights",
      "href": "#products"
    },
    {
      "label": "Enquire",
      "href": "#enquiry"
    }
  ],
  "assets": {
    "collection": "medical",
    "root": "/assets/medical",
    "framesDirectory": "/assets/medical/frames",
    "productsDirectory": "/assets/medical/products"
  },
  "hero": {
    "directory": "/assets/medical/frames",
    "poster": "/assets/medical/frames/ezgif-frame-001.jpg",
    "filePrefix": "ezgif-frame-",
    "fileExtension": "jpg",
    "framePadding": 3,
    "firstFrame": 1,
    "frameCount": 300,
    "width": 1920,
    "height": 1080,
    "scrollHeightVh": 600,
    "maxDevicePixelRatio": 2,
    "maxCachedFrames": 48,
    "loadConcurrency": 6,
    "narrowViewportBreakpoint": 768,
    "focalPoint": {
      "wide": {
        "x": 0.5,
        "y": 0.5
      },
      "narrow": {
        "x": 0.62,
        "y": 0.5
      }
    },
    "chapters": [
      {
        "id": "opening",
        "from": 0,
        "to": 0.24,
        "align": "left",
        "showScrollCue": true,
        "eyebrow": "Welcome to Al Barsha",
        "heading": "NHS Medical Fitness Center",
        "body": "A modern dental clinic dedicated to general and cosmetic care, designed to make every visit feel calm, clean, and reassuring for families and young professionals alike."
      },
      {
        "id": "mid",
        "from": 0.34,
        "to": 0.6,
        "align": "right",
        "eyebrow": "Distinctive Care",
        "heading": "Precision Meets Comfort",
        "body": "From routine cleanings and fillings to root canals, teeth whitening, and Invisalign orthodontics, we combine trusted clinical expertise with a welcoming environment that respects your time and comfort."
      },
      {
        "id": "closing",
        "from": 0.72,
        "to": 1,
        "align": "left",
        "eyebrow": "Your Next Step",
        "heading": "Ready for a Healthier Smile?",
        "body": "We are open Saturday to Thursday, 9am to 7pm, and accept most major insurance providers. Reach out today to schedule your consultation and begin your journey toward confident, healthy teeth.",
        "primaryCta": {
          "label": "Book an Appointment",
          "href": "#enquiry"
        },
        "secondaryCta": {
          "label": "View Services",
          "href": "#products"
        }
      }
    ]
  },
  "productsSection": {
    "id": "products",
    "eyebrow": "Our Capabilities",
    "heading": "Comprehensive Dental Solutions",
    "body": "We integrate advanced technology with personalized care to address a wide range of dental needs, ensuring accurate diagnoses and effective treatments for every patient.",
    "scrollHeightVh": 500,
    "items": [
      {
        "category": "Diagnostics",
        "name": "Advanced Medical Imaging",
        "description": "Utilizing high-resolution imaging technology to provide precise diagnostics for cleanings, fillings, and complex procedures like root canals, ensuring accurate treatment planning.",
        "image": "advanced-medical-imaging.jpg"
      },
      {
        "category": "Treatment Planning",
        "name": "Laboratory Analysis",
        "description": "Detailed analysis of oral health conditions to support tailored cosmetic and general dental care, including assessments for teeth whitening and Invisalign orthodontics.",
        "image": "laboratory-analysis.jpg"
      },
      {
        "category": "Orthodontics",
        "name": "Orthopaedic Joint Care",
        "description": "Specialized attention to jaw alignment and bite mechanics, integral to successful Invisalign treatments and overall oral health for families and professionals.",
        "image": "orthopaedic-joint-care.jpg"
      },
      {
        "category": "Patient Experience",
        "name": "Patient Monitoring",
        "description": "Continuous follow-up and progress tracking to ensure long-term success of treatments, from routine cleanings to comprehensive cosmetic transformations.",
        "image": "patient-monitoring.jpg"
      }
    ]
  }
} satisfies SiteConfig;
